service: serverlessfizzbuzz
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2

functions:
  fizzbuzz:
    handler: handler.fizzbuzz
    events:
      - http:
          path: fizzbuzz
          method: post
